import { useState, useEffect } from "react";

/* const barriosCordobaCapital = [
  "Alta Córdoba",
  "General Paz",
  "Nueva Córdoba",
  "Centro",
  "San Vicente",
  "Alberdi",
  "Observatorio",
  "Pueyrredón",
  "Jardín",
  "General Bustos",
  "Quinta Santa Ana",
  "Müller",
  "Matienzo",
  "Yofre",
  "Villa Cabrera",
  "Villa Belgrano",
  "Villa Libertador",
  "Poeta Lugones",
  "Pablo VI",
  "Ampliación San Vicente",
  "Villa Corina",
  "Cerro de las Rosas",
  "Lomas de San Martín",
]; */

const barriosCordobaCapital = [
  "Alta Córdoba",
  "Alberdi",
  "Altamira",
  "Ampliación Ferreyra",
  "Ampliación Los Boulevares",
  "Ampliación Pueyrredón",
  "Ampliación San Vicente",
  "Argüello",
  "Bancarios",
  "Barrio General Bustos",
  "Barrio Güemes",
  "Barrio Inaudi",
  "Barrio IPV Argüello",
  "Barrio Juan XXIII (La Quinta)",
  "Barrio Liceo",
  "Barrio Los Granados",
  "Barrio Maipú",
  "Barrio Providencia",
  "Barrio San Martín",
  "Barrio SEP",
  "Barrio Talleres Este",
  "Barrio Talleres Oeste",
  "Centro",
  "Cerro de las Rosas",
  "Chacabuco",
  "Chateau Carreras",
  "Ciudad Universitaria",
  "Cofico",
  "Colón",
  "Crisol",
  "Empalme",
  "General Bustos",
  "General Paz",
  "General Paz Sur",
  "Guiñazú",
  "Jardín",
  "Lomas de la Carolina",
  "Lomas de San Martín",
  "Los Boulevares",
  "Los Naranjos",
  "Los Plátanos",
  "Manantiales",
  "Marqués de Sobremonte",
  "Matienzo",
  "Mercantil",
  "Müller",
  "Nueva Córdoba",
  "Observatorio",
  "Parque Capital",
  "Parque Vélez Sarsfield",
  "Pablo VI",
  "Poeta Lugones",
  "Providencia",
  "Pueyrredón",
  "Quinta Santa Ana",
  "Residencial América",
  "Rogelio Martínez",
  "Rosedal",
  "San Fernando",
  "San Martín",
  "San Rafael",
  "San Salvador",
  "San Vicente",
  "Santa Isabel",
  "Urca",
  "Villa Allende Parque",
  "Villa Azalais",
  "Villa Belgrano",
  "Villa Cabrera",
  "Villa Corina",
  "Villa El Libertador",
  "Villa Esquiú",
  "Villa Libertador",
  "Villa Rivera Indarte",
  "Villa Warcalde",
  "Yofre",
];


export default function useDepartamentos() {
  const [departamentos, setDepartamentos] = useState([]);

  useEffect(() => {
    // Usar los barrios predefinidos directamente
    setDepartamentos(barriosCordobaCapital);
  }, []);

  return departamentos;
}
